In [60]:
using CondaPkg
CondaPkg.add("scipy")
CondaPkg.add("requests")
CondaPkg.add("inspect")
CondaPkg.add("subprocess")

    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Resolving changes
             + scipy
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.
    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.
    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Resolving changes
             + inspect
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ inspect = "*"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
Error:
  × failed to solve the conda requirements of 'default' 'osx-arm64'
  ╰─▶ Cannot solve the request because of: No candidates were found for
      inspect *.


    CondaPkg Resolve failed, reverting /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml

LoadError: failed process: Process(setenv(`/Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi install --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml`,["_CE_M=", "PATH=/Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin:/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/bin:/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/condabin:/Users/manabu/miniforge3/envs/py314/bin:/Users/manabu/.bun/bin:/Users/manabu/.local/bin:/Users/manabu/.juliaup/bin:/Users/manabu/miniforge3/condabin:/opt/homebrew/bin:/opt/homebrew/sbin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Library/Apple/usr/bin:/usr/local/go/bin:/Users/manabu/.cargo/bin:/Users/manabu/.docker/bin", "CONDA_PREFIX_1=/Users/manabu/miniforge3", "PYTHON_JULIACALL_INIT=no", "OPENBLAS_DEFAULT_NUM_THREADS=1", "USER=manabu", "PIXI_CACHE_DIR=/Users/manabu/.julia/scratchspaces/992eb4ea-22a4-4c89-a5bb-47a3300528ab/pixi_cache", "CONDA_PROMPT_MODIFIER=(/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default) ", "JPY_SESSION_NAME=/Users/manabu/work/ggblab/julia/GeoGebra.jl/examples/eg23_julia.ipynb", "COLUMNS=80"  …  "BUN_INSTALL=/Users/manabu/.bun", "PWD=/Users/manabu/work/ggblab", "TERM_PROGRAM=Apple_Terminal", "XML_CATALOG_FILES=file:///Users/manabu/miniforge3/etc/xml/catalog file:///etc/xml/catalog file:///Users/manabu/miniforge3/envs/py314/etc/xml/catalog file:///etc/xml/catalog", "JPY_PARENT_PID=13443", "MAMBA_EXE=/Users/manabu/miniforge3/bin/mamba", "CONDA_PREFIX=/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default", "TERM_SESSION_ID=EE75CA5F-0DCE-4308-917E-3165758CE8FC", "MAMBA_ROOT_PREFIX=/Users/manabu/miniforge3", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

In [1]:
using CondaPkg
CondaPkg.add_pip("juliacall")

    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.

In [36]:
using CondaPkg
# CondaPkg.rm_pip("ggblab")
CondaPkg.add_pip("ggblab", version="@ file:///Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl")

    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.

In [3]:
# ENV["GGBLAB_DISABLE_PERSISTENT_COUNTER"] = "1"

In [1]:
using Pkg
# Pkg.add("PyCall")
# Pkg.add("SymPy")
# Pkg.add("SymPyCore")
# Pkg.add("SymPyPythonCall")
# Pkg.add("Logging")
# Pkg.add("UUIDs")
# Pkg.add("IJulia")
# Pkg.add("JSON")
# Pkg.add("Observables")
# Pkg.add("Sockets")

In [1]:
using Pkg
Pkg.activate("/Users/manabu/work/ggblab/julia/GeoGebra.jl")  # または Pkg.activate(pwd())
Pkg.instantiate()
using GeoGebra

  Activating project at `~/work/ggblab/julia/GeoGebra.jl`

In [2]:
get_kernel_id()

"ee0bd04e-fa41-4952-b6be-038b0473fe79"

In [47]:
IJulia.CommManager.comms

Dict{String, IJulia.Comm} with 3 entries:
  "5106b90b-098c-4835-829d… => Comm{Symbol("jupyter.widget.control")}("5106b90b…
  "9e1e75ed-2eaf-4fb0-8846… => Comm{Symbol("jupyter.ggblab")}("9e1e75ed-2eaf-4f…
  "a5abf52d-786b-43d3-befb… => Comm{:webio_comm}("a5abf52d-786b-43d3-befb-4bd2a…

In [49]:
GeoGebra.COMM_REGISTRY

Dict{String, IJuliaConnection} with 1 entry:
  "9e1e75ed-2eaf-4fb0-8846… => IJuliaConnection(Comm{Symbol("jupyter.ggblab")}(…

In [51]:
list_registered_comm_keys()

1-element Vector{String}:
 "9e1e75ed-2eaf-4fb0-8846-ee5bf17307b1"

In [4]:
# ENV["JULIA_DEBUG"] = "all"

In [3]:
inject_applet() #useWs=true)

[ Info: Listening on: 127.0.0.1:50996, thread id: 1

Dict{String, Any} with 5 entries:
  "kernelId"   => "ee0bd04e-fa41-4952-b6be-038b0473fe79"
  "wsPort"     => 0xc734
  "insertMode" => "split-right"
  "type"       => "inject"
  "appName"    => "suite"

In [5]:
# p1 = GeoGebra.send_command("O = (0,0)")
# p2 = GeoGebra.send_command("P = (1,1)")
# p1, p2

In [4]:
@ggb :const

Tuple{Int64, String, Any}[]

In [5]:
@ggb O = (0,0)

O

Info: PersistentCounter disabled when called from Julia/PythonCall

In [6]:
@ggb :const

1-element Vector{Tuple{Int64, String, String}}:
 (1, "O", "(0, 0)")

In [7]:
@ggb r = Slider[0,3]

r

In [8]:
@ggb :c = Circle(:O, r)

c

In [9]:
@ggb A = (1,0)

A

In [10]:
@ggb B = (0, 1)

B

In [11]:
@ggb Line(:A, :B)

f

In [12]:
@ggb {Intersect(c,f)}

l1

In [13]:
@ggb :const

7-element Vector{Tuple{Int64, String, Any}}:
 (1, "O", "(0, 0)")
 (2, "r", nothing)
 (3, "c", "Circle(O, r)")
 (4, "A", "(1, 0)")
 (5, "B", "(0, 1)")
 (6, "f", "Line(A, B)")
 (7, "l1", "{Intersect(c, f)}")

In [49]:
obs = @ggb :listen :l1

Observable{Any}(nothing)

In [50]:
typeof(obs)

Observable{Any}

In [51]:
using Observables

In [58]:
hdr = on(obs) do v
    println("$v")
end

ObserverFunction defined at In[58]:2 operating on Observable{Any}("l1 = {(?, ?)}")

l1 = {(0.7645751311065, 0.2354248688935), (0.2354248688935, 0.7645751311065)}
l1 = {(0.8937003937006, 0.1062996062994), (0.1062996062994, 0.8937003937006)}
l1 = {(0.7645751311065, 0.2354248688935), (0.2354248688935, 0.7645751311065)}
l1 = {(?, ?)}
l1 = {(0.7645751311065, 0.2354248688935), (0.2354248688935, 0.7645751311065)}
l1 = {(0.8937003937006, 0.1062996062994), (0.1062996062994, 0.8937003937006)}
l1 = {(1, 0), (0, 1)}
l1 = {(0.8937003937006, 0.1062996062994), (0.1062996062994, 0.8937003937006)}
l1 = {(1, 0), (0, 1)}
l1 = {(0.8937003937006, 0.1062996062994), (0.1062996062994, 0.8937003937006)}
l1 = {(0.7645751311065, 0.2354248688935), (0.2354248688935, 0.7645751311065)}
l1 = {(?, ?)}

In [65]:
hdr = (function()
    pv = 0
    return on(obs) do v
        cv = length(PyList(ggb.parser.tokenize(v))[3])
        if pv != cv
            println(cv)
            pv = cv
        end
    end
end)()

ObserverFunction defined at In[65]:4 operating on Observable{Any}("l1 = {(?, ?)}")

2
0
2
0

In [63]:
typeof(hdr)

ObserverFunction

In [66]:
off(hdr)

true

In [48]:
remove_object_observable("l1")

In [67]:
@ggb :unlisten :l1

In [ ]:
# using PythonCall

# struct PyGeoGebra
#     file::Py
#     parser::Py
#     schema::Py
#     function PyGeoGebra()
#         file = pyimport("ggblab.file").ggb_file()
#         parser = pyimport("ggblab.parser").ggb_parser()
#         schema = pyimport("ggblab.schema").ggb_schema()
#         new(file, parser, schema)
#     end
# end

# ggb = PyGeoGebra()

In [28]:
PyList(ggb.parser.tokenize("l1 = {(1, -1.3747727084868), (1, 1.3747727084868)}"))

3-element PyList{Py}:
 'l1'
 '='
 [['1', '-1.3747727084868'], ['1', '1.3747727084868']]

In [72]:
ggb.file

Python: <ggblab.file.ggb_file object at 0x31e255f20>

In [12]:
@ggb :api getVersion()

"5.4.916.2"

## WebIO.jl and JSExper.jl

In [68]:
using Pkg

In [72]:
Pkg.add(url="https://github.com/moyhig-ecs/WebIO.jl.git")

     Cloning git-repo `https://github.com/moyhig-ecs/WebIO.jl.git`
    Updating git-repo `https://github.com/moyhig-ecs/WebIO.jl.git`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
      Compat entries added for
    Updating `~/work/ggblab/julia/GeoGebra.jl/Project.toml`
  [0f1e0344] ~ WebIO v0.8.21 ⇒ v0.8.21 `https://github.com/moyhig-ecs/WebIO.jl.git#apply-compare-0556c09`
    Updating `~/work/ggblab/julia/GeoGebra.jl/Manifest.toml`
  [0f1e0344] ~ WebIO v0.8.21 ⇒ v0.8.21 `https://github.com/moyhig-ecs/WebIO.jl.git#apply-compare-0556c09`
    Building WebIO → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/de43ba098521a007be1ed28b5a50379dce5e1a62/build.log`
Precompiling packages...
   1862.8 ms  ✓ WebIO
   1340.9 ms  ✓ JSExpr
  2 dependencies successfully precompiled in 4 seconds. 105 already precompiled.

In [73]:
using WebIO, JSExpr

WebIO._IJuliaInit()

In [74]:
function random_print_button()
    w = Scope()

    obs = Observable(w, "rand-value", 0.0)

    on(obs) do x
        println("JS sent $x")
    end

    w(
      dom"button"(
        "generate random",
        events=Dict("click"=>@js () -> $obs[] = Math.random()),
      ),
    )
end

random_print_button (generic function with 1 method)

In [75]:
random_print_button()

Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :button), Any["generate random"], Dict{Symbol, Any}(:events => Dict{String, JSString}("click" => JSString("(function (){return WebIO.setval({\"name\":\"rand-value\",\"scope\":\"15596239698907013451\",\"id\":\"3\",\"type\":\"observable\"},Math.random())})")))), Dict{String, Tuple{AbstractObservable, Union{Nothing, Bool}}}("rand-value" => (Observable(0.0), nothing)), Set{String}(), nothing, Asset[], Dict{Any, Any}(), WebIO.ConnectionPool(Channel{Any}(32), Set{WebIO.AbstractConnection}(), Base.GenericCondition(ReentrantLock())), JSString[])

JS sent 0.8231116190221875
JS sent 0.6494765272702876
JS sent 0.04585485742779816
JS sent 0.3935735692019038
JS sent 0.9143243506643177
JS sent 0.06864204377209981

In [76]:
w = Scope()

Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :span), Any[], Dict{Symbol, Any}()), Dict{String, Tuple{AbstractObservable, Union{Nothing, Bool}}}(), Set{String}(), nothing, Asset[], Dict{Any, Any}(), WebIO.ConnectionPool(Channel{Any}(32), Set{WebIO.AbstractConnection}(), Base.GenericCondition(ReentrantLock())), JSString[])

In [77]:
typeof(w)

Scope

In [78]:
obs = Observable(w, "slider-value", 0.0)

Observable(0.0)

In [88]:
n = Node(:input, 
    type=:range,
    attributes=Dict(
        :min => 0,
        :max => 100,
        :value => obs[],
    ),
    events=Dict(
        :input => @js (e) -> $obs[] = parseFloat(e.target.value)
    )
)

w(n)

Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :input), Any[], Dict{Symbol, Any}(:attributes => Dict{Symbol, Real}(:max => 100, :value => 34.0, :min => 0), :type => :range, :events => Dict{Symbol, JSString}(:input => JSString("(function (e){return WebIO.setval({\"name\":\"slider-value\",\"scope\":\"1932103671924909269\",\"id\":\"4\",\"type\":\"observable\"},parseFloat(e.target.value))})")))), Dict{String, Tuple{AbstractObservable, Union{Nothing, Bool}}}("slider-value" => (Observable(34.0), nothing)), Set{String}(), nothing, Asset[], Dict{Any, Any}(), WebIO.ConnectionPool(Channel{Any}(32), Set(WebIO.AbstractConnection[WebIO.IJuliaConnection(IJulia.Comm{:webio_comm}("8e856151-2fc0-4fab-b27f-f8647b1944a4", false, WebIO.var"#68#69"{WebIO.IJuliaConnection}(WebIO.IJuliaConnection(#= circular reference @-3 =#)), Returns{Nothing}(nothing)))]), Base.GenericCondition(ReentrantLock())), JSString[])

In [5]:
# v1 = GeoGebra.send_function("getVersion")

## call from PythonCall.jl using JuliaCall.py

In [14]:
using PythonCall
uj = pyimport("ggblab.utils_julia")
uj.called_from_julia()

Python: True

In [16]:
uj.jl_function_sync("getVersion")

Python: '5.4.916.2'

## write df with ConstructionIO

In [17]:
ggb = pyimport("ggblab")
ggb.file = pyimport("ggblab.file").ggb_file()
ggb.parser = pyimport("ggblab.parser").ggb_parser()
ggb.schema = pyimport("ggblab.schema").ggb_schema()

Python: <ggblab.schema.ggb_schema object at 0x327fd7750>

Info: PersistentCounter disabled when called from Julia/PythonCall

In [26]:
ggbex = pyimport("ggblab_extra")
ConstructionIO = ggbex.ConstructionIO
ConstructionTreeParser = ggbex.ConstructionTreeParser

Python: <class 'ggblab_extra.construction_parser.ConstructionTreeParser'>

In [19]:
df = @await ConstructionIO.initialize_dataframe(ggb, use_applet=true)

Python:
shape: (7, 10)
┌──────────┬──────┬─────────┬───────────────────┬───┬───────┬────────────┬─────…
│ Sequence ┆ Name ┆ Type    ┆ Command           ┆ … ┆ Layer ┆ ShowObject ┆ Show…
│ ---      ┆ ---  ┆ ---     ┆ ---               ┆   ┆ ---   ┆ ---        ┆ --- …
│ u32      ┆ str  ┆ str     ┆ str               ┆   ┆ u32   ┆ bool       ┆ bool…
╞══════════╪══════╪═════════╪═══════════════════╪═══╪═══════╪════════════╪═════…
│ 1        ┆ O    ┆ point   ┆ (0, 0)            ┆ … ┆ 0     ┆ false      ┆ fals…
│ 2        ┆ r    ┆ numeric ┆ null              ┆ … ┆ 0     ┆ true       ┆ true…
│ 3        ┆ c    ┆ circle  ┆ Circle(O, r)      ┆ … ┆ 0     ┆ true       ┆ true…
│ 4        ┆ A    ┆ point   ┆ (1, 0)            ┆ … ┆ 0     ┆ false      ┆ fals…
│ 5        ┆ B    ┆ point   ┆ (0, 1)            ┆ … ┆ 0     ┆ false      ┆ fals…
│ 6        ┆ f    ┆ line    ┆ Line(A, B)        ┆ … ┆ 0     ┆ true       ┆ true…
│ 7        ┆ l1   ┆ list    ┆ {Intersect(c, f)} ┆ … ┆ 0     ┆ true       ┆ true…
└──────────┴──────┴─────────┴───────────────────┴───┴───────┴────────────┴─────…

Info: PersistentCounter disabled when called from Julia/PythonCall

## Similarity

In [27]:
df2 = ConstructionTreeParser(df)

Python: <ggblab_extra.construction_parser.ConstructionTreeParser object at 0x332c19a90>

Info: PersistentCounter disabled when called from Julia/PythonCall

In [28]:
g = df2.parse()

Python: <networkx.classes.digraph.DiGraph object at 0x332c2efd0>

In [29]:
nx = pyimport("networkx")

Python: <module 'networkx' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/networkx/__init__.py'>

In [30]:
nx.write_network_text(g)

Python: None

╟── O
╎   └─╼ c ╾ r
╎       └─╼ l1 ╾ f
╟── r
╎   └─╼  ...
╟── A
╎   └─╼ f ╾ B
╎       └─╼  ...
╟── B
╎   └─╼  ...
╙── l1

In [31]:
graph_similarity = pyimport("ggblab_extra.graph_similarity")

Python: <module 'ggblab_extra.graph_similarity' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab_extra/graph_similarity.py'>

In [33]:
graph_similarity.hungarian_similarity(g, g)

Python: (np.float64(1.0), {'ref_nodes': ['R0', 'R1', 'R2', 'R3', 'R4', 'R5', 'R6', 'R7'], 'sub_nodes': ['S0', 'S1', 'S2', 'S3', 'S4', 'S5', 'S6', 'S7'], 'collapse_report': {'ref_map': {'l1__list': 'R0', 'c': 'R1', 'O': 'R2', 'r': 'R3', 'f': 'R4', 'A': 'R5', 'B': 'R6', 'l1': 'R7'}, 'sub_map': {'l1__list': 'S0', 'c': 'S1', 'O': 'S2', 'r': 'S3', 'f': 'S4', 'A': 'S5', 'B': 'S6', 'l1': 'S7'}, 'ref_members': {'R0': ['l1__list'], 'R1': ['c'], 'R2': ['O'], 'R3': ['r'], 'R4': ['f'], 'R5': ['A'], 'R6': ['B'], 'R7': ['l1']}, 'sub_members': {'S0': ['l1__list'], 'S1': ['c'], 'S2': ['O'], 'S3': ['r'], 'S4': ['f'], 'S5': ['A'], 'S6': ['B'], 'S7': ['l1']}}, 'matched_pairs': [('R0', 'S0'), ('R1', 'S1'), ('R2', 'S2'), ('R3', 'S3'), ('R4', 'S4'), ('R5', 'S5'), ('R6', 'S6'), ('R7', 'S7')], 'unmatched_ref': [], 'unmatched_sub': [], 'node_cost': 0.0, 'edge_penalty': 0, 'total_cost': 0.0, 'similarity': 1.0})

## SymPyPythonCall.jl

In [2]:
using PythonCall
pl = pyimport("polars")
ggbex_sympy = pyimport("ggblab_extra.sympy")

Python: <module 'ggblab_extra.sympy' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab_extra/sympy/__init__.py'>

Info: PersistentCounter disabled when called from Julia/PythonCall

In [21]:
df2 = ggbex_sympy.attach_object2d(df)["Name", "Type", "object2d"]

Python:
shape: (7, 3)
┌──────┬─────────┬─────────────────────────────────┐
│ Name ┆ Type    ┆ object2d                        │
│ ---  ┆ ---     ┆ ---                             │
│ str  ┆ str     ┆ object                          │
╞══════╪═════════╪═════════════════════════════════╡
│ O    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ r    ┆ numeric ┆ null                            │
│ c    ┆ circle  ┆ Object2D(kind='circle', obj=Ci… │
│ A    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ B    ┆ point   ┆ Object2D(kind='point', obj=Poi… │
│ f    ┆ line    ┆ Object2D(kind='line', obj=Line… │
│ l1   ┆ list    ┆ null                            │
└──────┴─────────┴─────────────────────────────────┘

In [22]:
f = df2.filter(pl.col("Name").is_in(["f"]))["object2d"].item()

Python: Object2D(kind='line', obj=Line2D(Point2D(0, 1), Point2D(1, 0)), value='f: -x - y = -1', command='Line(A, B)')

In [1]:
using SymPyPythonCall

In [105]:
eq = ggbex_sympy.circle_from_value("c: x² + y² = 0.49").equation()

Python: x**2 + y**2 - 49/100

In [106]:
eq.free_symbols

Python: {x, y}

In [196]:
x, y = pybuiltins.sorted(eq.free_symbols, key=pystr)

Python: [x, y]

In [107]:
# x, y = sort([s for s in eq.free_symbols], by=s->Symbol(s))

2-element Vector{Py}:
 x
 y

In [189]:
subs(Sym(eq), Dict(x => 1, y => 2))

451
───
100

In [116]:
Sym(eq)(x=>1, y=>2)

451
───
100

In [191]:
@syms x y

(x, y)

In [192]:
typeof(Py(x))

Py

In [194]:
dump(Py(x))

Py
  ptr: Ptr{Nothing}(0x0000000325e11c90)

In [195]:
dump(x)

Sym{Py}
  o: Py
    ptr: Ptr{Nothing}(0x000000013c6b40e0)

In [197]:
dump(x)

Py
  ptr: Ptr{Nothing}(0x000000031c0aee30)

In [198]:
dump(Sym(x))

Sym{Py}
  o: Py
    ptr: Ptr{Nothing}(0x000000031c0aee30)

In [173]:
methods(subs)

# 11 methods for generic function "subs" from SymPyCore:
  [1] subs(dict::Dict; kwargs...)
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:101
  [2] subs(exs::Tuple{T, N}, args...; kwargs...) where {T<:SymPyCore.SymbolicObject, N}
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:95
  [3] subs(ex::T, d::Pair...; kwargs...) where T<:SymPyCore.SymbolicObject
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:94
  [4] subs(ex::T, y::Tuple{Any, Any}; kwargs...) where T<:SymPyCore.SymbolicObject
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:85
  [5] subs(ex::T, y::Tuple{Any, Any}, args...; kwargs...) where T<:SymPyCore.SymbolicObject
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:91
  [6] subs(ex::T, dict::Dict; kwargs...) where T<:SymPyCore.SymbolicObject
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:93
  [7] subs(x::SymPyCore.SymbolicObject, y; kwargs...)
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:99
  [8] subs(ex::T, y::S, val; kwargs...) where {T<:SymPyCore.SymbolicObject, S<:SymPyCore.SymbolicObject}
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:92
  [9] subs(x::Number, args...; kwargs...)
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:96
 [10] subs(; kwargs...)
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:100
 [11] subs(d::Pair...; kwargs...)
     @ ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:102

In [176]:
@which subs(Sym(eq), Dict(x => 1))

subs(ex::T, dict::Dict; kwargs...) where T<:SymPyCore.SymbolicObject
     @ SymPyCore ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:93

In [182]:
@which subs(Sym(eq), x => 1, y => 2)

subs(ex::T, d::Pair...; kwargs...) where T<:SymPyCore.SymbolicObject
     @ SymPyCore ~/.julia/packages/SymPyCore/l4Bbg/src/utils.jl:94

In [113]:
seq = Sym(eq)
x, y = sort([s for s in seq.free_symbols], by=s->Symbol(s))
seq |> subs(x, 1) |> subs(y, 2)

451
───
100

In [117]:
sp = pyimport("sympy")

Python: <module 'sympy' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/sympy/__init__.py'>

In [169]:
sp.print_tree(x)

Python: None

Symbol: x
commutative: True
complex: True
extended_real: True
finite: True
hermitian: True
imaginary: False
infinite: False
real: True

In [172]:
eq

Python: x**2 + y**2 - 49/100

In [168]:
sp.print_tree(eq, assumptions=false)

Python: None

Add: x**2 + y**2 - 49/100
+-Rational: -49/100
+-Pow: x**2
| +-Symbol: x
| +-Integer: 2
+-Pow: y**2
  +-Symbol: y
  +-Integer: 2

In [162]:
sp.print_mathml(eq, printer="presentation")

Python: None

<mrow>
	<msup>
		<mi>x</mi>
		<mn>2</mn>
	</msup>
	<mo>+</mo>
	<msup>
		<mi>y</mi>
		<mn>2</mn>
	</msup>
	<mo>-</mo>
	<mfrac>
		<mn>49</mn>
		<mn>100</mn>
	</mfrac>
</mrow>

In [159]:
display(HTML("""<math xmlns="http://www.w3.org/1998/Math/MathML">"""*string(sp.mathml(eq, printer="presentation"))*"</math>"))

HTML{String}("<math xmlns=\"http://www.w3.org/1998/Math/MathML\"><mrow><msup><mi>x</mi><mn>2</mn></msup><mo>+</mo><msup><mi>y</mi><mn>2</mn></msup><mo>-</mo><mfrac><mn>49</mn><mn>100</mn></mfrac></mrow></math>")

In [163]:
sp.print_latex(eq)

Python: None

x^{2} + y^{2} - \frac{49}{100}

In [152]:
display("text/latex", string(raw"$", sp.latex(eq), raw"$"))