In [1]:
using CondaPkg
CondaPkg.add("scipy")
CondaPkg.add("requests")
CondaPkg.add("inspect")
CondaPkg.add("subprocess")

    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │ requests = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.
    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │ requests = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.
    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Resolving changes
             + inspect
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ inspect = "*"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │ requests = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
Error:
  × failed to solve the conda requirements of 'default' 'osx-arm64'
  ╰─▶ Cannot solve the request because of: No candidates were found for
      inspect *.


    CondaPkg Resolve failed, reverting /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml

LoadError: failed process: Process(setenv(`/Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi install --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml`,["_CE_M=", "PATH=/Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin:/Users/manabu/miniforge3/envs/py314/bin:/Users/manabu/.juliaup/bin:/opt/homebrew/bin:/opt/homebrew/sbin:/Users/manabu/miniforge3/condabin:/usr/local/anaconda3/bin:/usr/local/bin:/System/Cryptexes/App/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin:/var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin:/opt/pmk/env/global/bin:/Library/Apple/usr/bin:/usr/local/share/dotnet:~/.dotnet/tools:/Library/Frameworks/Mono.framework/Versions/Current/Commands", "CONDA_PREFIX_1=/Users/manabu/miniforge3", "OPENBLAS_DEFAULT_NUM_THREADS=1", "USER=manabu", "PIXI_CACHE_DIR=/Users/manabu/.julia/scratchspaces/992eb4ea-22a4-4c89-a5bb-47a3300528ab/pixi_cache", "CONDA_PROMPT_MODIFIER=(py314) ", "JPY_SESSION_NAME=/Users/manabu/work/ggblab/julia/GeoGebra.jl/examples/eg23_julia.ipynb", "COLUMNS=80", "SHELL=/bin/bash"  …  "TERM_PROGRAM_VERSION=466", "PWD=/Users/manabu/work/ggblab", "TERM_PROGRAM=Apple_Terminal", "XML_CATALOG_FILES=file:///Users/manabu/miniforge3/etc/xml/catalog file:///etc/xml/catalog", "JPY_PARENT_PID=63653", "MAMBA_EXE=/Users/manabu/miniforge3/bin/mamba", "CONDA_PREFIX=/Users/manabu/miniforge3/envs/py314", "TERM_SESSION_ID=CA58F971-58D0-4304-8F0C-9EF71A12DC91", "MAMBA_ROOT_PREFIX=/Users/manabu/miniforge3", "OPENBLAS_MAIN_FREE=1"]), ProcessExited(1)) [1]

KeyError: KeyError: key "37e3c775-485e-444b-9fe5-a77a28fc3ddf" not found

In [42]:
using CondaPkg
CondaPkg.add_pip("juliacall")

    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │ requests = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.

In [43]:
using CondaPkg
# CondaPkg.rm_pip("ggblab")
CondaPkg.add_pip("ggblab", version="@ file:///Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl")

    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │ requests = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.

In [3]:
# ENV["GGBLAB_DISABLE_PERSISTENT_COUNTER"] = "1"

In [1]:
using Pkg
# Pkg.add("PyCall")
# Pkg.add("SymPy")
# Pkg.add("SymPyCore")
# Pkg.add("SymPyPythonCall")
# Pkg.add("Logging")
# Pkg.add("UUIDs")
# Pkg.add("IJulia")
# Pkg.add("JSON")
# Pkg.add("Observables")
# Pkg.add("Sockets")

In [1]:
using Pkg
Pkg.activate("/Users/manabu/work/ggblab/julia/GeoGebra.jl")  # または Pkg.activate(pwd())
Pkg.instantiate()
using GeoGebra

  Activating project at `~/work/ggblab/julia/GeoGebra.jl`

In [2]:
# get_kernel_id()

"a11b79d5-9331-4bd7-a038-4a92fdda7e54"

In [3]:
# ENV["JULIA_DEBUG"] = "all"

In [3]:
?inject_applet() #useWs=true)

[ Info: Listening on: 127.0.0.1:51031, thread id: 1

Dict{String, Any} with 5 entries:
  "kernelId"   => "a11b79d5-9331-4bd7-a038-4a92fdda7e54"
  "wsPort"     => 0xc757
  "insertMode" => "split-right"
  "type"       => "inject"
  "appName"    => "suite"

In [5]:
# p1 = GeoGebra.send_command("O = (0,0)")
# p2 = GeoGebra.send_command("P = (1,1)")
# p1, p2

In [4]:
using SymPyPythonCall

@syms θ
m = [cos(θ) -sin(θ) 0; sin(θ) cos(θ) 0; 0 0 1]
string(m)

"Sym{PythonCall.Py}[cos(θ) -sin(θ) 0; sin(θ) cos(θ) 0; 0 0 1]"

In [5]:
GeoGebra.sympy_to_ggb(m)

"{{cos(θ), -sin(θ), 0}, {sin(θ), cos(θ), 0}, {0, 0, 1}}"

In [6]:
@syms λx λy

(λx, λy)

In [7]:
@ggb λx = Slider[-5, 5]

λx

Info: PersistentCounter disabled when called from Julia/PythonCall

In [8]:
@ggb λy = Slider[-5, 5]

λy

In [10]:
λ = [1 λx 0; λy 1 0; 0 0 1]

3×3 Matrix{Sym{PythonCall.Py}}:
  1  λx  0
 λy   1  0
  0   0  1

In [11]:
@ggb :λ = λ

λ

In [2]:
@ggb O = (0,0)

O

Info: PersistentCounter disabled when called from Julia/PythonCall

In [3]:
@ggb A = (1, 0)

A

In [4]:
@ggb B = (0, 1)

B

In [16]:
@ggb Polygon(:O, :A, :B)

4-element Vector{GGBObject}:
 t1
 b
 o
 a

In [18]:
@ggb ApplyMatrix(:λ, :t1)

4-element Vector{GGBObject}:
 t1'
 b'
 o'
 a'

In [ ]:
Λ

In [19]:
typeof(↑)

typeof(↑) (singleton type of function ↑, subtype of Function)

In [53]:
GeoGebra.expr_to_cmd_string("2 π")

"2 π"

In [52]:
typeof(ℯ)

Irrational{:ℯ}

In [58]:
2 * π

6.283185307179586

In [55]:
@ggb θ = Slider(0, 2π)

θ

In [9]:
@ggb :m = m

m

In [10]:
# @ggb m

In [11]:
@ggb :const :undo

In [12]:
@ggb :const

1-element Vector{Tuple{Int64, String, Nothing}}:
 (1, "θ", nothing)

In [13]:
@ggb O = (0,0)

O

In [14]:
@ggb :const

2-element Vector{Tuple{Int64, String, Any}}:
 (1, "θ", nothing)
 (2, "O", "(0, 0)")

In [15]:
@ggb r = Slider(0,3)

r

In [16]:
@ggb :c = Circle(:O, r)

c

In [17]:
@ggb A = (1,0)

A

In [18]:
@ggb B = (0, 1)

B

In [19]:
@ggb Line(:A, :B)

f

In [20]:
@ggb {Intersect(c,f)}

l1

In [21]:
@ggb :const

8-element Vector{Tuple{Int64, String, Any}}:
 (1, "θ", nothing)
 (2, "O", "(0, 0)")
 (3, "r", nothing)
 (4, "c", "Circle(O, r)")
 (5, "A", "(1, 0)")
 (6, "B", "(0, 1)")
 (7, "f", "Line(A, B)")
 (8, "l1", "{Intersect(c, f)}")

In [22]:
obs = @ggb :listen :l1

Observable{Any}("l1 = {(?, ?)}")

In [23]:
typeof(obs)

Observables.Observable{Any}

In [24]:
using Observables

In [25]:
hdr = on(obs) do v
    println("$v")
end

ObserverFunction defined at In[25]:2 operating on Observable{Any}("l1 = {(1.8228756555323, -0.8228756555323), (-0.8228756555323, 1.8228756555323)}")

l1 = {(1.898213145411, -0.898213145411), (-0.898213145411, 1.898213145411)}
l1 = {(1.8228756555323, -0.8228756555323), (-0.8228756555323, 1.8228756555323)}
l1 = {(1.746996391334, -0.746996391334), (-0.746996391334, 1.746996391334)}
l1 = {(1.8228756555323, -0.8228756555323), (-0.8228756555323, 1.8228756555323)}
l1 = {(1.898213145411, -0.898213145411), (-0.898213145411, 1.898213145411)}
l1 = {(1.8228756555323, -0.8228756555323), (-0.8228756555323, 1.8228756555323)}
l1 = {(1.746996391334, -0.746996391334), (-0.746996391334, 1.746996391334)}
l1 = {(1.670469991072, -0.670469991072), (-0.670469991072, 1.670469991072)}

In [65]:
hdr = (function()
    pv = 0
    return on(obs) do v
        cv = length(PyList(ggb.parser.tokenize(v))[3])
        if pv != cv
            println(cv)
            pv = cv
        end
    end
end)()

ObserverFunction defined at In[65]:4 operating on Observable{Any}("l1 = {(?, ?)}")

2
0
2
0

In [63]:
typeof(hdr)

ObserverFunction

In [26]:
off(hdr)

true

In [27]:
# remove_object_observable("l1")

In [28]:
@ggb :unlisten :l1

In [ ]:
# using PythonCall

# struct PyGeoGebra
#     file::Py
#     parser::Py
#     schema::Py
#     function PyGeoGebra()
#         file = pyimport("ggblab.file").ggb_file()
#         parser = pyimport("ggblab.parser").ggb_parser()
#         schema = pyimport("ggblab.schema").ggb_schema()
#         new(file, parser, schema)
#     end
# end

# ggb = PyGeoGebra()

In [30]:
ggb.parser.tokenize("l1 = {(1, -1.3747727084868), (1, 1.3747727084868)}")

LoadError: UndefVarError: `ggb` not defined in `Main`
Suggestion: check for spelling errors or missing imports.

In [72]:
ggb.file

Python: <ggblab.file.ggb_file object at 0x31e255f20>

In [11]:
@ggb :api getVersion()

"5.4.916.2"

In [68]:
using Pkg

In [72]:
Pkg.add(url="https://github.com/moyhig-ecs/WebIO.jl.git")

     Cloning git-repo `https://github.com/moyhig-ecs/WebIO.jl.git`
    Updating git-repo `https://github.com/moyhig-ecs/WebIO.jl.git`
    Updating registry at `~/.julia/registries/General.toml`
   Resolving package versions...
      Compat entries added for
    Updating `~/work/ggblab/julia/GeoGebra.jl/Project.toml`
  [0f1e0344] ~ WebIO v0.8.21 ⇒ v0.8.21 `https://github.com/moyhig-ecs/WebIO.jl.git#apply-compare-0556c09`
    Updating `~/work/ggblab/julia/GeoGebra.jl/Manifest.toml`
  [0f1e0344] ~ WebIO v0.8.21 ⇒ v0.8.21 `https://github.com/moyhig-ecs/WebIO.jl.git#apply-compare-0556c09`
    Building WebIO → `~/.julia/scratchspaces/44cfe95a-1eb2-52ea-b672-e2afdf69b78f/de43ba098521a007be1ed28b5a50379dce5e1a62/build.log`
Precompiling packages...
   1862.8 ms  ✓ WebIO
   1340.9 ms  ✓ JSExpr
  2 dependencies successfully precompiled in 4 seconds. 105 already precompiled.

In [73]:
using WebIO, JSExpr

WebIO._IJuliaInit()

In [74]:
function random_print_button()
    w = Scope()

    obs = Observable(w, "rand-value", 0.0)

    on(obs) do x
        println("JS sent $x")
    end

    w(
      dom"button"(
        "generate random",
        events=Dict("click"=>@js () -> $obs[] = Math.random()),
      ),
    )
end

random_print_button (generic function with 1 method)

In [75]:
random_print_button()

Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :button), Any["generate random"], Dict{Symbol, Any}(:events => Dict{String, JSString}("click" => JSString("(function (){return WebIO.setval({\"name\":\"rand-value\",\"scope\":\"15596239698907013451\",\"id\":\"3\",\"type\":\"observable\"},Math.random())})")))), Dict{String, Tuple{AbstractObservable, Union{Nothing, Bool}}}("rand-value" => (Observable(0.0), nothing)), Set{String}(), nothing, Asset[], Dict{Any, Any}(), WebIO.ConnectionPool(Channel{Any}(32), Set{WebIO.AbstractConnection}(), Base.GenericCondition(ReentrantLock())), JSString[])

JS sent 0.8231116190221875
JS sent 0.6494765272702876
JS sent 0.04585485742779816
JS sent 0.3935735692019038
JS sent 0.9143243506643177
JS sent 0.06864204377209981

In [76]:
w = Scope()

Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :span), Any[], Dict{Symbol, Any}()), Dict{String, Tuple{AbstractObservable, Union{Nothing, Bool}}}(), Set{String}(), nothing, Asset[], Dict{Any, Any}(), WebIO.ConnectionPool(Channel{Any}(32), Set{WebIO.AbstractConnection}(), Base.GenericCondition(ReentrantLock())), JSString[])

In [77]:
typeof(w)

Scope

In [78]:
obs = Observable(w, "slider-value", 0.0)

Observable(0.0)

In [88]:
n = Node(:input, 
    type=:range,
    attributes=Dict(
        :min => 0,
        :max => 100,
        :value => obs[],
    ),
    events=Dict(
        :input => @js (e) -> $obs[] = parseFloat(e.target.value)
    )
)

w(n)

Scope(Node{WebIO.DOM}(WebIO.DOM(:html, :input), Any[], Dict{Symbol, Any}(:attributes => Dict{Symbol, Real}(:max => 100, :value => 34.0, :min => 0), :type => :range, :events => Dict{Symbol, JSString}(:input => JSString("(function (e){return WebIO.setval({\"name\":\"slider-value\",\"scope\":\"1932103671924909269\",\"id\":\"4\",\"type\":\"observable\"},parseFloat(e.target.value))})")))), Dict{String, Tuple{AbstractObservable, Union{Nothing, Bool}}}("slider-value" => (Observable(34.0), nothing)), Set{String}(), nothing, Asset[], Dict{Any, Any}(), WebIO.ConnectionPool(Channel{Any}(32), Set(WebIO.AbstractConnection[WebIO.IJuliaConnection(IJulia.Comm{:webio_comm}("8e856151-2fc0-4fab-b27f-f8647b1944a4", false, WebIO.var"#68#69"{WebIO.IJuliaConnection}(WebIO.IJuliaConnection(#= circular reference @-3 =#)), Returns{Nothing}(nothing)))]), Base.GenericCondition(ReentrantLock())), JSString[])

In [5]:
# v1 = GeoGebra.send_function("getVersion")

In [32]:
using PythonCall
uj = pyimport("ggblab.utils_julia")
uj.called_from_julia()

Python: True

In [33]:
uj.jl_function_sync("getVersion")

Python: '5.4.916.2'

In [17]:
ggb_uj = pyimport("ggblab.utils_julia")

Python: <module 'ggblab.utils_julia' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab/utils_julia.py'>

In [18]:
ggb_uj.called_from_julia()

Python: True

In [19]:
ggb_uj.jl_command_sync("(1,1)")

Python: 'C'

In [26]:
ggbex_cio = pyimport("ggblab_extra.construction_io")

Python: <module 'ggblab_extra.construction_io' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab_extra/construction_io.py'>

In [27]:
ggb

LoadError: UndefVarError: `ggb` not defined in `Main`
Suggestion: add an appropriate import or assignment. This global was declared but not assigned.

In [6]:
using PythonCall

In [7]:
ggb = pyimport("ggblab")
ggb.file = pyimport("ggblab.file").ggb_file()
ggb.parser = pyimport("ggblab.parser").ggb_parser()
ggb.schema = pyimport("ggblab.schema").ggb_schema()

Python: <ggblab.schema.ggb_schema object at 0x317264e90>

Info: PersistentCounter disabled when called from Julia/PythonCall

In [8]:
ggbex = pyimport("ggblab_extra")
ConstructionIO = ggbex.ConstructionIO
ConstructionParser = ggbex.ConstructionTreeParser

Python: <class 'ggblab_extra.construction_parser.ConstructionTreeParser'>

In [9]:
df = @await ConstructionIO.initialize_dataframe(ggb, use_applet=true)

Python:
shape: (3, 10)
┌──────────┬──────┬───────┬─────────┬───┬───────┬────────────┬───────────┬─────…
│ Sequence ┆ Name ┆ Type  ┆ Command ┆ … ┆ Layer ┆ ShowObject ┆ ShowLabel ┆ Auxi…
│ ---      ┆ ---  ┆ ---   ┆ ---     ┆   ┆ ---   ┆ ---        ┆ ---       ┆ --- …
│ u32      ┆ str  ┆ str   ┆ str     ┆   ┆ u32   ┆ bool       ┆ bool      ┆ bool…
╞══════════╪══════╪═══════╪═════════╪═══╪═══════╪════════════╪═══════════╪═════…
│ 1        ┆ O    ┆ point ┆ (0, 0)  ┆ … ┆ 0     ┆ false      ┆ false     ┆ fals…
│ 2        ┆ A    ┆ point ┆ (1, 0)  ┆ … ┆ 0     ┆ false      ┆ false     ┆ fals…
│ 3        ┆ B    ┆ point ┆ (0, 1)  ┆ … ┆ 0     ┆ false      ┆ false     ┆ fals…
└──────────┴──────┴───────┴─────────┴───┴───────┴────────────┴───────────┴─────…

Info: PersistentCounter disabled when called from Julia/PythonCall

In [10]:
using PythonCall
pl = pyimport("polars")
ggbex_sympy = pyimport("ggblab_extra.sympy")

Python: <module 'ggblab_extra.sympy' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab_extra/sympy/__init__.py'>

In [11]:
df2 = ggbex_sympy.attach_object2d(df)["Name", "Type", "object2d"]

Python:
shape: (3, 3)
┌──────┬───────┬─────────────────────────────────┐
│ Name ┆ Type  ┆ object2d                        │
│ ---  ┆ ---   ┆ ---                             │
│ str  ┆ str   ┆ object                          │
╞══════╪═══════╪═════════════════════════════════╡
│ O    ┆ point ┆ Object2D(kind='point', obj=Poi… │
│ A    ┆ point ┆ Object2D(kind='point', obj=Poi… │
│ B    ┆ point ┆ Object2D(kind='point', obj=Poi… │
└──────┴───────┴─────────────────────────────────┘

In [12]:
f = df2.filter(pl.col("Name").is_in(["f"]))["object2d"].item()

LoadError: Python: ValueError: can only call '.item()' if the Series is of length 1, or an explicit index is provided (Series is of length 0)
Python stacktrace:
 [1] item
   @ polars.series.series ~/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/polars/series/series.py:1736

In [41]:
eq = ggbex_sympy.circle_from_value("c: x² + y² = 0.49").equation()

Python: x**2 + y**2 - 49/100

In [42]:
(eq.free_symbols)

Python: {x, y}

In [43]:
pybuiltins.sorted(eq.free_symbols, key=pystr)

Python: [x, y]

In [44]:
using SymPyPythonCall

In [17]:
@syms x::real

(x,)

In [45]:
df2 = ConstructionParser(df)

Python: <ggblab_extra.construction_parser.ConstructionTreeParser object at 0x324680d70>

Info: PersistentCounter disabled when called from Julia/PythonCall

In [46]:
g = df2.parse()

Python: <networkx.classes.digraph.DiGraph object at 0x324699e50>

In [47]:
nx = pyimport("networkx")

Python: <module 'networkx' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/networkx/__init__.py'>

In [48]:
nx.write_network_text(g)

Python: None

╟── O
╎   └─╼ c ╾ r
╎       └─╼ l1 ╾ f
╟── r
╎   └─╼  ...
╟── A
╎   └─╼ f ╾ B
╎       └─╼  ...
╟── B
╎   └─╼  ...
╙── l1

In [49]:
ggbex_similar = pyimport("ggblab_extra.graph_similarity")

Python: <module 'ggblab_extra.graph_similarity' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab_extra/graph_similarity.py'>

In [50]:
using SymPyPythonCall

In [51]:
# sp = pyimport("sympy")
sympy

<module 'sympy' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.p ↪

↪ ixi/envs/default/lib/python3.14/site-packages/sympy/__init__.py'>

In [7]:
GeoGebra.COMM_QUEUES

Dict{String, Channel{String}} with 1 entry:
  "06dc6382-6143-4be7-bea9-4de377f0994c" => Channel{String}(64)

In [8]:
comm_id = "06dc6382-6143-4be7-bea9-4de377f0994c"

"06dc6382-6143-4be7-bea9-4de377f0994c"

In [9]:
GeoGebra.peek_comm_queue(comm_id)

6-element Vector{String}:
 "{\"payload\":{},\"type\":\"start\"}"
 "{\"payload\":\"O\",\"type\":\"add\",\"ts\":1774233615489}"
 "{\"type\":\"created\",\"payload\":\"O\"" ⋯ 18 bytes ⋯ "8-2eab-4f01-a9f5-1e7af7031fdb\"}"
 "{\"type\":\"created\",\"payload\":\"P\"" ⋯ 18 bytes ⋯ "2-7084-4b5f-9b84-c25ce840b522\"}"
 "{\"type\":\"value\",\"payload\":{\"val" ⋯ 34 bytes ⋯ "2-d364-42f6-904b-ba0bb9ecd6ce\"}"
 "{\"type\":\"value\",\"payload\":{\"val" ⋯ 34 bytes ⋯ "e-37d0-4839-a492-d61c14668ff7\"}"

In [10]:
q = GeoGebra.get_observer_queue(comm_id)

In [12]:
q

In [19]:
GeoGebra

GeoGebra

In [8]:
using PythonCall

In [39]:
@pyexec """
global jl
# global pyggb_send_command
from juliacall import Main as jl
def pyggb_send_command(c):
   return jl.GeoGebra.send_command(c)
""" => pyggb_send_command

Python: <function pyggb_send_command at 0x15393bcc0>

In [36]:
@pyexec """
from juliacall import Main as jl
def pyggb_send_command(c):
   return jl.GeoGebra.send_command(c)
p = pyggb_send_command("A = (0,0)")
print(p)
"""

┌ Info: comm_direct: awaiting reply
│   req_id = "2b4fb798-19c0-4303-860f-e7c7ef7de2c0"
│   keys_pending =
│    1-element Vector{String}:
└     "2b4fb798-19c0-4303-860f-e7c7ef7de2c0"

[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"created","payload":"A","req_id":"2b4fb798-19c0-4303-860f-e7c7ef7de2c0"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235573562857e9
[comm_direct] data to enqueue: {"req_id":"2b4fb798-19c0-4303-860f-e7c7ef7de2c0","payload":"A","type":"created"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235573565272e9 response: Dict{String, Any}("req_id" => "2b4fb798-19c0-4303-860f-e7c7ef7de2c0", "payload" => "A", "type" => "created")
A
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.77423557357016e9
[comm_direct] data to enqueue: {"type":"created","payload":"A","req_id":"2b4fb798-19c0-4303-860f-e7c7ef7de2c0"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235573570342e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "2b4fb798-19c0-4303-860f-e7c7ef7de2c0"
└   keys_pending = String[]

In [33]:
pyggb_send_command("A = (0, 0)")

[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"created","payload":"A","req_id":"fe101767-319d-4ed2-97f9-69c83dc172b1"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235384741803e9
[comm_direct] data to enqueue: {"req_id":"fe101767-319d-4ed2-97f9-69c83dc172b1","payload":"A","type":"created"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235384746073e9 response: Dict{String, Any}("req_id" => "fe101767-319d-4ed2-97f9-69c83dc172b1", "payload" => "A", "type" => "created")

┌ Info: comm_direct: awaiting reply
│   req_id = "fe101767-319d-4ed2-97f9-69c83dc172b1"
│   keys_pending =
│    1-element Vector{String}:
└     "fe101767-319d-4ed2-97f9-69c83dc172b1"

Python: 'A'

[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235384750642e9
[comm_direct] data to enqueue: {"type":"created","payload":"A","req_id":"fe101767-319d-4ed2-97f9-69c83dc172b1"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235384750869e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "fe101767-319d-4ed2-97f9-69c83dc172b1"
└   keys_pending = String[]

In [31]:
@pyexec """
from juliacall import Main as jl
p = jl.GeoGebra.send_command("A = (0,0)")
print(p)
"""

┌ Info: comm_direct: awaiting reply
│   req_id = "bf6dd9c2-9cb5-43d6-8920-9020d518dffc"
│   keys_pending =
│    1-element Vector{String}:
└     "bf6dd9c2-9cb5-43d6-8920-9020d518dffc"

[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"created","payload":"A","req_id":"bf6dd9c2-9cb5-43d6-8920-9020d518dffc"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.77423533902405e9
[comm_direct] data to enqueue: {"req_id":"bf6dd9c2-9cb5-43d6-8920-9020d518dffc","payload":"A","type":"created"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235339029514e9 response: Dict{String, Any}("req_id" => "bf6dd9c2-9cb5-43d6-8920-9020d518dffc", "payload" => "A", "type" => "created")
A
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774235339033895e9
[comm_direct] data to enqueue: {"type":"created","payload":"A","req_id":"bf6dd9c2-9cb5-43d6-8920-9020d518dffc"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.77423533903411e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "bf6dd9c2-9cb5-43d6-8920-9020d518dffc"
└   keys_pending = String[]

In [22]:
x

1

In [10]:
GeoGebra.OBSERVER_QUEUES

Dict{String, Channel{String}}()

In [6]:
@ggb B = (0, 1)

┌ Info: comm_direct: awaiting reply
│   req_id = "09d4e7e2-1051-4115-b13d-cb208e944f2a"
│   keys_pending =
│    1-element Vector{String}:
└     "09d4e7e2-1051-4115-b13d-cb208e944f2a"

[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"created","payload":"B","req_id":"09d4e7e2-1051-4115-b13d-cb208e944f2a"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233953543709e9
[comm_direct] data to enqueue: {"req_id":"09d4e7e2-1051-4115-b13d-cb208e944f2a","payload":"B","type":"created"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233953555347e9 response: Dict{String, Any}("req_id" => "09d4e7e2-1051-4115-b13d-cb208e944f2a", "payload" => "B", "type" => "created")
[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"bulk_actions","payload":[{"type":"add","payload":"B","ts":1774233953532}]}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233953700034e9
[comm_direct] data to enqueue: {"payload":[{"payload":"B","type":"add","ts":1774233953532}],"type":"bulk_actions"}
[comm_direct] enqueued bulk_actions items for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99
[comm_ingest_ws] Client disconnected
[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"value","payload":{"value":"<expression label=\"B\" exp=\"(0, 1)\" type=\"point\"/>\n<element type=\"point\" label=\"B\">\n\t<show object=\"true\" label=\"true\"/>\n\t<objColor r=\"21\" g=\"101\" b=\"192\" alpha=\"0\"/>\n\t<layer val=\"0\"/>\n\t<labelMode val=\"0\"/>\n\t<animation step=\"0.1\" type=\"1\" playing=\"false\"/>\n\t<pointSize val=\"5\"/>\n\t<pointStyle val=\"0\"/>\n\t<coords x=\"0\" y=\"1\" z=\"1\"/>\n</element>\n"},"req_id":"1054664e-3aed-4317-bb41-91c1492f00b0"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233953707056e9
[comm_direct] data to enqueue: {"req_id":"1054664e-3aed-4317-bb41-91c1492f00b0","payload":{"value":"<expression label=\"B\" exp=\"(0, 1)\" type=\"point\"/>\n<element type=\"point\" label=\"B\">\n\t<show object=\"true\" label=\"true\"/>\n\t<objColor r=\"21\" g=\"101\" b=\"192\" alpha=\"0\"/>\n\t<layer val=\"0\"/>\n\t<labelMode val=\"0\"/>\n\t<animation step=\"0.1\" type=\"1\" playing=\"false\"/>\n\t<pointSize val=\"5\"/>\n\t<pointStyle val=\"0\"/>\n\t<coords x=\"0\" y=\"1\" z=\"1\"/>\n</element>\n"},"type":"value"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233953712113e9 response: Dict{String, Any}("req_id" => "1054664e-3aed-4317-bb41-91c1492f00b0", "payload" => Dict{String, Any}("value" => "<expression label=\"B\" exp=\"(0, 1)\" type=\"point\"/>\n<element type=\"point\" label=\"B\">\n\t<show object=\"true\" label=\"true\"/>\n\t<objColor r=\"21\" g=\"101\" b=\"192\" alpha=\"0\"/>\n\t<layer val=\"0\"/>\n\t<labelMode val=\"0\"/>\n\t<animation step=\"0.1\" type=\"1\" playing=\"false\"/>\n\t<pointSize val=\"5\"/>\n\t<pointStyle val=\"0\"/>\n\t<coords x=\"0\" y=\"1\" z=\"1\"/>\n</element>\n"), "type" => "value")

┌ Info: comm_direct: awaiting reply
│   req_id = "1054664e-3aed-4317-bb41-91c1492f00b0"
│   keys_pending =
│    1-element Vector{String}:
└     "1054664e-3aed-4317-bb41-91c1492f00b0"

B

Info: PersistentCounter disabled when called from Julia/PythonCall
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233954795797e9
[comm_direct] data to enqueue: {"type":"created","payload":"B","req_id":"09d4e7e2-1051-4115-b13d-cb208e944f2a"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233954795972e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "09d4e7e2-1051-4115-b13d-cb208e944f2a"
└   keys_pending = String[]

[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233954798921e9
[comm_direct] data to enqueue: {"type":"value","payload":{"value":"<expression label=\"B\" exp=\"(0, 1)\" type=\"point\"/>\n<element type=\"point\" label=\"B\">\n\t<show object=\"true\" label=\"true\"/>\n\t<objColor r=\"21\" g=\"101\" b=\"192\" alpha=\"0\"/>\n\t<layer val=\"0\"/>\n\t<labelMode val=\"0\"/>\n\t<animation step=\"0.1\" type=\"1\" playing=\"false\"/>\n\t<pointSize val=\"5\"/>\n\t<pointStyle val=\"0\"/>\n\t<coords x=\"0\" y=\"1\" z=\"1\"/>\n</element>\n"},"req_id":"1054664e-3aed-4317-bb41-91c1492f00b0"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233954799046e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "1054664e-3aed-4317-bb41-91c1492f00b0"
└   keys_pending = String[]

In [7]:
@ggb :const

[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"value","payload":{"value":null},"req_id":"405b93a7-cac3-409b-b2df-f89260e13c51"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972323488e9
[comm_direct] data to enqueue: {"req_id":"405b93a7-cac3-409b-b2df-f89260e13c51","payload":{"value":null},"type":"value"}
[comm_ingest_ws] Client disconnected

┌ Info: comm_direct: awaiting reply
│   req_id = "405b93a7-cac3-409b-b2df-f89260e13c51"
│   keys_pending =
│    1-element Vector{String}:
└     "405b93a7-cac3-409b-b2df-f89260e13c51"

[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972327449e9 response: Dict{String, Any}("req_id" => "405b93a7-cac3-409b-b2df-f89260e13c51", "payload" => Dict{String, Any}("value" => nothing), "type" => "value")
[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"value","payload":{"value":"(0, 1)"},"req_id":"9f4ebbb1-162d-4958-a8ee-bbc3e6604d47"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972354647e9
[comm_direct] data to enqueue: {"req_id":"9f4ebbb1-162d-4958-a8ee-bbc3e6604d47","payload":{"value":"(0, 1)"},"type":"value"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972361906e9 response: Dict{String, Any}("req_id" => "9f4ebbb1-162d-4958-a8ee-bbc3e6604d47", "payload" => Dict{String, Any}("value" => "(0, 1)"), "type" => "value")
[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"value","payload":{"value":null},"req_id":"90093b7c-01a9-407d-906f-1b9d00520773"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972399598e9
[comm_direct] data to enqueue: {"req_id":"90093b7c-01a9-407d-906f-1b9d00520773","payload":{"value":null},"type":"value"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.77423397240679e9 response: Dict{String, Any}("req_id" => "90093b7c-01a9-407d-906f-1b9d00520773", "payload" => Dict{String, Any}("value" => nothing), "type" => "value")

┌ Info: comm_direct: awaiting reply
│   req_id = "9f4ebbb1-162d-4958-a8ee-bbc3e6604d47"
│   keys_pending =
│    1-element Vector{String}:
└     "9f4ebbb1-162d-4958-a8ee-bbc3e6604d47"
┌ Info: comm_direct: awaiting reply
│   req_id = "90093b7c-01a9-407d-906f-1b9d00520773"
│   keys_pending =
│    1-element Vector{String}:
└     "90093b7c-01a9-407d-906f-1b9d00520773"
┌ Info: comm_direct: awaiting reply
│   req_id = "2dcfd708-c60f-4183-bf5e-c89296ae83c4"
│   keys_pending =
│    1-element Vector{String}:
└     "2dcfd708-c60f-4183-bf5e-c89296ae83c4"

[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"value","payload":{"value":null},"req_id":"2dcfd708-c60f-4183-bf5e-c89296ae83c4"}
[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972430953e9
[comm_direct] data to enqueue: {"req_id":"2dcfd708-c60f-4183-bf5e-c89296ae83c4","payload":{"value":null},"type":"value"}
[comm_ingest_ws] Client disconnected
[comm_direct] received reply for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972432511e9 response: Dict{String, Any}("req_id" => "2dcfd708-c60f-4183-bf5e-c89296ae83c4", "payload" => Dict{String, Any}("value" => nothing), "type" => "value")

4-element Vector{Tuple{Int64, String, Any}}:
 (1, "obj1", nothing)
 (2, "B", "(0, 1)")
 (3, "obj3", nothing)
 (4, "obj4", nothing)

[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.77423397257365e9
[comm_direct] data to enqueue: {"type":"value","payload":{"value":null},"req_id":"405b93a7-cac3-409b-b2df-f89260e13c51"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972573792e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "405b93a7-cac3-409b-b2df-f89260e13c51"
└   keys_pending = String[]

[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972574856e9
[comm_direct] data to enqueue: {"type":"value","payload":{"value":"(0, 1)"},"req_id":"9f4ebbb1-162d-4958-a8ee-bbc3e6604d47"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972575073e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "9f4ebbb1-162d-4958-a8ee-bbc3e6604d47"
└   keys_pending = String[]

[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972575981e9
[comm_direct] data to enqueue: {"type":"value","payload":{"value":null},"req_id":"90093b7c-01a9-407d-906f-1b9d00520773"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972576158e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "90093b7c-01a9-407d-906f-1b9d00520773"
└   keys_pending = String[]

[comm_direct] enqueue attempt for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972577067e9
[comm_direct] data to enqueue: {"type":"value","payload":{"value":null},"req_id":"2dcfd708-c60f-4183-bf5e-c89296ae83c4"}
[comm_direct] enqueued message for key:fefbbc96-115d-4ff3-b433-d605fd6f7b99 at 1.774233972577237e9
[comm_direct] COMM_QUEUES["fefbbc96-115d-4ff3-b433-d605fd6f7b99"]: Channel{String}(64)

┌ Info: comm_direct: incoming message with req_id
│   rid = "2dcfd708-c60f-4183-bf5e-c89296ae83c4"
└   keys_pending = String[]

In [9]:
@ggb :api getVersion()

[comm_ingest_ws] Client connected
[comm_ingest_ws] Received: {"type":"error","payload":{"message":"Unsupported command type"}}
[comm_direct] enqueue attempt for key:275a55c6-9aac-40cb-9ad1-0b96904042cd at 1.77423268513956e9
[comm_direct] data to enqueue: {"payload":{"message":"Unsupported command type"},"type":"error"}
[comm_direct] enqueued message for key:275a55c6-9aac-40cb-9ad1-0b96904042cd at 1.774232685139756e9
[comm_direct] COMM_QUEUES["275a55c6-9aac-40cb-9ad1-0b96904042cd"]: Channel{String}(64)
[comm_ingest_ws] Client disconnected

┌ Info: comm_direct: awaiting reply
│   req_id = "2c52b4ec-ba24-4a4b-a67a-4b8f397053b9"
│   keys_pending =
│    1-element Vector{String}:
└     "2c52b4ec-ba24-4a4b-a67a-4b8f397053b9"

LoadError: TaskFailedException

    nested task error: comm_direct: timeout waiting for reply for req_id 2c52b4ec-ba24-4a4b-a67a-4b8f397053b9
    Stacktrace:
     [1] _wait_on_pending(id::String; timeout::Float64)
       @ GeoGebra ~/work/ggblab/julia/GeoGebra.jl/src/comm_direct.jl:253
     [2] _wait_on_pending
       @ ~/work/ggblab/julia/GeoGebra.jl/src/comm_direct.jl:227 [inlined]
     [3] (::GeoGebra.var"#8#9"{Float64, String})()
       @ GeoGebra ~/work/ggblab/julia/GeoGebra.jl/src/comm_direct.jl:434

[comm_direct] enqueue attempt for key:275a55c6-9aac-40cb-9ad1-0b96904042cd at 1.774232695128737e9
[comm_direct] data to enqueue: {"type":"error","payload":{"message":"Unsupported command type"}}
[comm_direct] enqueued message for key:275a55c6-9aac-40cb-9ad1-0b96904042cd at 1.774232695129387e9
[comm_direct] COMM_QUEUES["275a55c6-9aac-40cb-9ad1-0b96904042cd"]: Channel{String}(64)

In [2]:
include("../src/comm_direct.jl")

IJulia.CommManager.register_comm

In [3]:
IJulia.CommManager.comms

Dict{String, IJulia.Comm} with 1 entry:
  "fe03dceb-013a-40b5-b8e8… => Comm{Symbol("jupyter.widget.control")}("fe03dceb…

In [4]:
COMM_REGISTRY

Dict{String, IJuliaConnection}()

In [5]:
include("../src/comm_control.jl")

get_kernel_id (generic function with 1 method)

In [6]:
get_kernel_id()

"ce4aaf47-8d50-40fb-b527-5f9184405f9a"

In [7]:
inject_applet()

Dict{String, AbstractString} with 4 entries:
  "kernelId"   => "ce4aaf47-8d50-40fb-b527-5f9184405f9a"
  "insertMode" => "split-right"
  "type"       => "inject"
  "appName"    => "suite"

In [8]:
IJulia.CommManager.comms

Dict{String, IJulia.Comm} with 2 entries:
  "fe03dceb-013a-40b5-b8e8… => Comm{Symbol("jupyter.widget.control")}("fe03dceb…
  "ebd42514-85b8-41a4-9018… => Comm{Symbol("jupyter.ggblab")}("ebd42514-85b8-41…

In [10]:
COMM_REGISTRY

Dict{String, IJuliaConnection} with 1 entry:
  "ebd42514-85b8-41a4-9018… => IJuliaConnection(Comm{Symbol("jupyter.ggblab")}(…

In [10]:
comm = nothing
for (k, v) in COMM_REGISTRY
    comm = COMM_REGISTRY[k]
end

In [15]:
list_registered_comm_keys()[1]

"ebd42514-85b8-41a4-9018-80e285ed8284"

In [19]:
comm

IJuliaConnection(IJulia.Comm{Symbol("jupyter.ggblab")}("be497a77-a705-4856-ab41-aee3ef685897", false, var"#5#6"{IJuliaConnection}(IJuliaConnection(#= circular reference @-3 =#)), Returns{Nothing}(nothing)))

In [18]:
COMM_REGISTRY[comm]

IJuliaConnection(IJulia.Comm{Symbol("jupyter.ggblab")}("ebd42514-85b8-41a4-9018-80e285ed8284", false, var"#5#6"{IJuliaConnection}(IJuliaConnection(#= circular reference @-3 =#)), Returns{Nothing}(nothing)))

LoadError: MethodError: no method matching getindex(::typeof(list_registered_comm_keys), ::Int64)
The function `getindex` exists, but no method is defined for this combination of argument types.

In [19]:
using JSON
using UUIDs

comm = COMM_REGISTRY[list_registered_comm_keys()[1]]
# data = Dict("type" => "function", "payload" => Dict("name" => "getVersion", "args" => ""))
data = Dict("type" => "command", "payload" => "O = (0, 0)")
msg = Dict("id" => string(uuid4()), "data" => data)

Dict{String, Any} with 2 entries:
  "id"   => "c9924d2f-b5c4-44e2-9394-cd2d3150652c"
  "data" => Dict("payload"=>"O = (0, 0)", "type"=>"command")

In [20]:
IJulia.send_comm(comm.comm, msg)

[comm_direct] received message:{"type":"created","payload":"O"}

In [13]:
comm = IJulia.Comm("jupyter.ggblab.control")
IJulia.send_comm(comm, Dict("type"=>"inject", "insertMode"=>"split-right"))

In [6]:
comm = open_control_comm()

IJulia.Comm{Symbol("jupyter.ggblab.control")}("6aca3a41-b81e-4603-ba99-7e2a011e3bb8", true, Returns{Nothing}(nothing), Returns{Nothing}(nothing))

In [10]:
payload = Dict("type"=>"inject", "kernelId"=>kernel_id, "insertMode"=>"split-right", "appName"=>"suite")

Dict{String, AbstractString} with 4 entries:
  "kernelId"   => "ce4aaf47-8d50-40fb-b527-5f9184405f9a"
  "insertMode" => "split-right"
  "type"       => "inject"
  "appName"    => "suite"

In [11]:
        IJulia_mod = nothing
        try
            if !isdefined(Main, :IJulia)
                Base.require(Main, :IJulia)
            end
            IJulia_mod = getfield(Main, :IJulia)
        catch
            IJulia_mod = nothing
        end

        JSON_mod = nothing
        try
            if !isdefined(Main, :JSON)
                Base.require(Main, :JSON)
            end
            JSON_mod = getfield(Main, :JSON)
        catch
            JSON_mod = nothing
        end

        if IJulia_mod === nothing
            throw(ErrorException("IJulia not available; cannot send comm message"))
        end

        # Use `IJulia.send_comm` only (user confirmed no `send`).
        if !hasproperty(IJulia_mod, :send_comm)
            throw(ErrorException("IJulia has no comm send function `send_comm`"))
        end
        send_fn = getfield(IJulia_mod, :send_comm)

LoadError: IJulia has no comm send function `send_comm`

In [12]:
IJulia.send_comm()

LoadError: MethodError: no method matching send_comm()
The function `send_comm` exists, but no method is defined for this combination of argument types.

Closest candidates are:
  send_comm(::IJulia.Comm, ::Dict; ...)
   @ IJulia ~/.julia/packages/IJulia/Vl5w1/src/comm_manager.jl:66
  send_comm(::IJulia.Comm, ::Dict, ::Dict; ...)
   @ IJulia ~/.julia/packages/IJulia/Vl5w1/src/comm_manager.jl:66
  send_comm(::IJulia.Comm, ::Dict, ::Dict, ::Any; kernel, kwargs...)
   @ IJulia ~/.julia/packages/IJulia/Vl5w1/src/comm_manager.jl:66

In [14]:
hasproperty(IJulia_mod, :send_comm)

false

In [15]:
send_fn = getfield(IJulia_mod, :send_comm)

send_comm (generic function with 3 methods)

In [2]:
@ggb O = (0, 0)

O

Info: PersistentCounter disabled when called from Julia/PythonCall