In [1]:
using CondaPkg
# CondaPkg.rm_pip("ggblab")
CondaPkg.add_pip("ggblab", version="@ file:///Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl")

    CondaPkg Found dev dependencies: /Users/manabu/work/ggblab/julia/GeoGebra.jl/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/SymPyPythonCall/pwFVP/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/PythonCall/83z4q/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/packages/CondaPkg/0UqYV/CondaPkg.toml
    CondaPkg Found dependencies: /Users/manabu/.julia/environments/v1.12/CondaPkg.toml
    CondaPkg Initialising pixi
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ init
             │ --format pixi
             └ /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg
✔ Created /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
    CondaPkg Wrote /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
             │ [dependencies]
             │ openssl = ">=3, <3.6"
             │ uv = ">=0.4"
             │ sympy = "*"
             │ requests = "*"
             │ scipy = "*"
             │
             │     [dependencies.python]
             │     channel = "conda-forge"
             │     build = "*cp*"
             │     version = ">=3.10,!=3.14.0,!=3.14.1,<4"
             │
             │ [project]
             │ name = ".CondaPkg"
             │ platforms = ["osx-arm64"]
             │ channels = ["conda-forge"]
             │ channel-priority = "strict"
             │ description = "automatically generated by CondaPkg.jl"
             │
             │ [pypi-dependencies]
             │ juliacall = "*"
             │
             │     [pypi-dependencies.ggblab]
             └     path = "/Users/manabu/work/ggblab/dist/ggblab-1.7.5-py3-none-any.whl"
    CondaPkg Installing packages
             │ /Users/manabu/.julia/artifacts/d2fecc2a9fa3eac2108d3e4d9d155e6ff5dfd0b2/bin/pixi
             │ install
             └ --manifest-path /Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/pixi.toml
✔ The default environment has been installed.

In [2]:
# ENV["JULIA_DEBUG"]="GeoGebra"

In [1]:
using Pkg
Pkg.activate("/Users/manabu/work/ggblab/julia/GeoGebra.jl")  # または Pkg.activate(pwd())
Pkg.instantiate()
# Pkg.precompile()
using GeoGebra

  Activating project at `~/work/ggblab/julia/GeoGebra.jl`
Precompiling packages...
   3299.2 ms  ✓ GeoGebra
  1 dependency successfully precompiled in 4 seconds. 94 already precompiled.

In [2]:
ENV["GGB_DIRECT_TRANSPORT"] = true

true

In [3]:
inject_applet()

[ Info: Listening on: 127.0.0.1:53438, thread id: 1

Dict{String, Any} with 5 entries:
  "kernelId"   => "2189422d-b077-48ca-ab94-5a89f5d06aef"
  "wsPort"     => 0xd0be
  "insertMode" => "split-right"
  "type"       => "inject"
  "appName"    => "suite"

┌ Warning: comm_ingest_ws: no registered comms to route message to
└ @ GeoGebra ~/work/ggblab/julia/GeoGebra.jl/src/comm_ingest_ws.jl:98

In [4]:
versioninfo()

Julia Version 1.12.5
Commit 5fe89b8ddc1 (2026-02-09 16:05 UTC)
Build Info:
  Official https://julialang.org release
Platform Info:
  OS: macOS (arm64-apple-darwin24.0.0)
  CPU: 24 × Apple M2 Ultra
  WORD_SIZE: 64
  LLVM: libLLVM-18.1.7 (ORCJIT, apple-m2)
  GC: Built with stock GC
Threads: 1 default, 1 interactive, 1 GC (on 16 virtual cores)

In [11]:
@ggb :api getVersion()

"5.4.916.2"

┌ Info: comm_ingest_ws: idle timeout reached, poking listener to restart
└   idle = 3.0
┌ Info: comm_ingest_ws: periodic restart due; poking listener to restart
└   interval = 10.0

In [9]:
@ggb :const :new

GGBObject[]

In [7]:
@ggb A = (0, -8, 0)
@ggb B = (6, 0, 0)
@ggb C = (-6, 0, 0)

C

Info: PersistentCounter disabled when called from Julia/PythonCall

In [8]:
@ggb Polygon(:A, :B, :C)

4-element Vector{GGBObject}:
 t1
 c
 a
 b

In [9]:
@ggb I = TriangleCenter(:A, :B, :C, 1)
@ggb G = TriangleCenter(:A, :B, :C, 2)

G

In [11]:
@ggb PerpendicularLine(:G, :xOyPlane)

g

In [12]:
@ggb P = Point(f)

P

In [13]:
@ggb Segment(:P, :A)
@ggb Segment(:P, :B)
@ggb Segment(:P, :C)

j

In [14]:
@ggb Line(:A, :I)

k

In [56]:
@ggb D = Intersect(:k, :a)

D

In [16]:
@ggb Circle(:P, :D, :I)

d

In [64]:
@ggb {Intersect(:d, :h)}

l3

In [61]:
@ggb E = l2(1)

E

In [19]:
@ggb Angle(:P, :E, :D)

α

In [20]:
@ggb Angle(:P, :I, :D)

β

In [21]:
@ggb Segment(:E, :D)
@ggb Segment(:P, :I)

m

In [22]:
@ggb "xyPlane = xOyPlane"
@ggb yzPlane = Plane(:yAxis, :zAxis)

yzPlane

In [65]:
@ggb :const

36-element Vector{Tuple{Int64, String, Py}}:
 (1, "A", '(0, -8, 0)')
 (2, "B", '(6, 0, 0)')
 (3, "C", '(-6, 0, 0)')
 (4, "t1", 'Polygon(A, B, C)')
 (5, "c", 'Segment(A, B, t1)')
 (6, "a", 'Segment(B, C, t1)')
 (7, "b", 'Segment(C, A, t1)')
 (8, "I", 'TriangleCenter(A, B, C, 1)')
 (9, "G", 'TriangleCenter(A, B, C, 2)')
 (10, "f", 'PerpendicularLine(G, xOyPlane)')
 (11, "g", 'PerpendicularLine(G, xOyPlane)')
 (12, "P", 'Point(f)')
 (13, "h", 'Segment(P, A)')
 ⋮
 (25, "xyPlane", 'xOyPlane')
 (26, "yzPlane", 'Plane(yAxis, zAxis)')
 (27, "E", 'l2(1)')
 (28, "E", 'l2(1)')
 (29, "D", 'Intersect(k, a)')
 (30, "D", 'Intersect(k, a)')
 (31, "E", 'l2(1)')
 (32, "E", 'l2(1)')
 (33, "l2", '{Intersect(h, d)}')
 (34, "E", 'l2(1)')
 (35, "E", 'l2(1)')
 (36, "l3", '{Intersect(h, d)}')

In [24]:
using PythonCall

In [25]:
ggb = pyimport("ggblab")
ggb.file = pyimport("ggblab.file").ggb_file()
ggb.parser = pyimport("ggblab.parser").ggb_parser()
ggb.schema = pyimport("ggblab.schema").ggb_schema()

Python: <ggblab.schema.ggb_schema object at 0x375eae210>

Info: PersistentCounter disabled when called from Julia/PythonCall

In [26]:
ggbex = pyimport("ggblab_extra")
ConstructionIO = ggbex.ConstructionIO
ConstructionTreeParser = ggbex.ConstructionTreeParser

Python: <class 'ggblab_extra.construction_parser.ConstructionTreeParser'>

In [36]:
ggbex_sympy.set_applet_3d(true)

Python: None

In [37]:
ggbex_sympy.get_applet_3d()

Python: True

In [66]:
df = @await ConstructionIO.initialize_dataframe(ggb, use_applet=true)

Python:
shape: (28, 10)
┌──────────┬─────────┬──────────┬─────────────────┬───┬───────┬────────────┬───…
│ Sequence ┆ Name    ┆ Type     ┆ Command         ┆ … ┆ Layer ┆ ShowObject ┆ Sh…
│ ---      ┆ ---     ┆ ---      ┆ ---             ┆   ┆ ---   ┆ ---        ┆ --…
│ u32      ┆ str     ┆ str      ┆ str             ┆   ┆ u32   ┆ bool       ┆ bo…
╞══════════╪═════════╪══════════╪═════════════════╪═══╪═══════╪════════════╪═══…
│ 1        ┆ A       ┆ point    ┆ (0, -8, 0)      ┆ … ┆ 0     ┆ false      ┆ fa…
│ 2        ┆ B       ┆ point    ┆ (6, 0, 0)       ┆ … ┆ 0     ┆ false      ┆ fa…
│ 3        ┆ C       ┆ point    ┆ (-6, 0, 0)      ┆ … ┆ 0     ┆ false      ┆ fa…
│ 4        ┆ t1      ┆ triangle ┆ Polygon(A, B,   ┆ … ┆ 0     ┆ true       ┆ fa…
│          ┆         ┆          ┆ C)              ┆   ┆       ┆            ┆   …
│ 5        ┆ c       ┆ segment  ┆ Segment(A, B,   ┆ … ┆ 0     ┆ true       ┆ fa…
│          ┆         ┆          ┆ t1)             ┆   ┆       ┆            ┆   …
                             ... 22 more lines ...
│          ┆         ┆          ┆ d)}             ┆   ┆       ┆            ┆   …
│ 21       ┆ E       ┆ point    ┆ l2(1)           ┆ … ┆ 0     ┆ true       ┆ tr…
│ 22       ┆ α       ┆ angle    ┆ Angle(P, E, D)  ┆ … ┆ 0     ┆ true       ┆ tr…
│ 23       ┆ β       ┆ angle    ┆ Angle(P, I, D)  ┆ … ┆ 0     ┆ true       ┆ tr…
│ 24       ┆ l       ┆ segment  ┆ Segment(E, D)   ┆ … ┆ 0     ┆ true       ┆ fa…
│ 25       ┆ m       ┆ segment  ┆ Segment(P, I)   ┆ … ┆ 0     ┆ true       ┆ fa…
│ 26       ┆ xyPlane ┆ plane    ┆ xOyPlane        ┆ … ┆ 0     ┆ false      ┆ fa…
│ 27       ┆ yzPlane ┆ plane    ┆ Plane(yAxis,    ┆ … ┆ 0     ┆ false      ┆ fa…
│          ┆         ┆          ┆ zAxis)          ┆   ┆       ┆            ┆   …
│ 28       ┆ l3      ┆ list     ┆ {Intersect(h,   ┆ … ┆ 0     ┆ true       ┆ fa…
│          ┆         ┆          ┆ d)}             ┆   ┆       ┆            ┆   …
└──────────┴─────────┴──────────┴─────────────────┴───┴───────┴────────────┴───…

In [28]:
pl = pyimport("polars")
ggbex_sympy = pyimport("ggblab_extra.sympy")

Python: <module 'ggblab_extra.sympy' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab_extra/sympy/__init__.py'>

In [38]:
df2 = ggbex_sympy.attach_object3d(df)["Name", "Type", "Command", "Value", "object3d"]

Python:
shape: (26, 5)
┌─────────┬──────────┬─────────────────────────┬─────────────────────────┬─────…
│ Name    ┆ Type     ┆ Command                 ┆ Value                   ┆ obje…
│ ---     ┆ ---      ┆ ---                     ┆ ---                     ┆ --- …
│ str     ┆ str      ┆ str                     ┆ str                     ┆ obje…
╞═════════╪══════════╪═════════════════════════╪═════════════════════════╪═════…
│ A       ┆ point    ┆ (0, -8, 0)              ┆ A = (0, -8, 0)          ┆ Obje…
│         ┆          ┆                         ┆                         ┆ obj=…
│ B       ┆ point    ┆ (6, 0, 0)               ┆ B = (6, 0, 0)           ┆ Obje…
│         ┆          ┆                         ┆                         ┆ obj=…
│ C       ┆ point    ┆ (-6, 0, 0)              ┆ C = (-6, 0, 0)          ┆ Obje…
│         ┆          ┆                         ┆                         ┆ obj=…
│ t1      ┆ triangle ┆ Polygon(A, B, C)        ┆ t1 = 48                 ┆ Obje…
                             ... 33 more lines ...
│         ┆          ┆                         ┆                         ┆ obj=…
│ β       ┆ angle    ┆ Angle(P, I, D)          ┆ β = 88.73°              ┆ Obje…
│         ┆          ┆                         ┆                         ┆ obj=…
│ l       ┆ segment  ┆ Segment(E, D)           ┆ l = 9.4                 ┆ Obje…
│         ┆          ┆                         ┆                         ┆ , ob…
│ m       ┆ segment  ┆ Segment(P, I)           ┆ m = 6.73                ┆ Obje…
│         ┆          ┆                         ┆                         ┆ , ob…
│ xyPlane ┆ plane    ┆ xOyPlane                ┆ xyPlane: z = 0          ┆ Obje…
│         ┆          ┆                         ┆                         ┆ obj=…
│ yzPlane ┆ plane    ┆ Plane(yAxis, zAxis)     ┆ yzPlane: x = 0          ┆ Obje…
│         ┆          ┆                         ┆                         ┆ obj=…
└─────────┴──────────┴─────────────────────────┴─────────────────────────┴─────…

In [67]:
df3 = ggbex_sympy.enumerate_plane_members(df2)
    # df2.filter(pl.col("Type").is_in(["point", "plane"]))

Python:
shape: (26, 6)
┌─────────┬──────────┬────────────────────┬────────────────────┬───────────────…
│ Name    ┆ Type     ┆ Command            ┆ Value              ┆ object3d      …
│ ---     ┆ ---      ┆ ---                ┆ ---                ┆ ---           …
│ str     ┆ str      ┆ str                ┆ str                ┆ object        …
╞═════════╪══════════╪════════════════════╪════════════════════╪═══════════════…
│ A       ┆ point    ┆ (0, -8, 0)         ┆ A = (0, -8, 0)     ┆ Object3D(kind=…
│         ┆          ┆                    ┆                    ┆ int', obj=Poi……
│ B       ┆ point    ┆ (6, 0, 0)          ┆ B = (6, 0, 0)      ┆ Object3D(kind=…
│         ┆          ┆                    ┆                    ┆ int', obj=Poi……
│ C       ┆ point    ┆ (-6, 0, 0)         ┆ C = (-6, 0, 0)     ┆ Object3D(kind=…
│         ┆          ┆                    ┆                    ┆ int', obj=Poi……
│ t1      ┆ triangle ┆ Polygon(A, B, C)   ┆ t1 = 48            ┆ Object3D(kind=…
                             ... 34 more lines ...
│         ┆          ┆                    ┆                    ┆ e, obj=None, ……
│ β       ┆ angle    ┆ Angle(P, I, D)     ┆ β = 88.73°         ┆ Object3D(kind=…
│         ┆          ┆                    ┆                    ┆ e, obj=None, ……
│ l       ┆ segment  ┆ Segment(E, D)      ┆ l = 9.4            ┆ Object3D(kind=…
│         ┆          ┆                    ┆                    ┆ gment', obj=S……
│ m       ┆ segment  ┆ Segment(P, I)      ┆ m = 6.73           ┆ Object3D(kind=…
│         ┆          ┆                    ┆                    ┆ gment', obj=S……
│ xyPlane ┆ plane    ┆ xOyPlane           ┆ xyPlane: z = 0     ┆ Object3D(kind=…
│         ┆          ┆                    ┆                    ┆ ane', obj=Pla……
│ yzPlane ┆ plane    ┆ Plane(yAxis,       ┆ yzPlane: x = 0     ┆ Object3D(kind=…
│         ┆          ┆ zAxis)             ┆                    ┆ ane', obj=Pla……
└─────────┴──────────┴────────────────────┴────────────────────┴───────────────…

In [68]:
pylist(df3[-1]["plane_members"])

Python:
[shape: (11,)
Series: '' [str]
[
	"A"
	"I"
	"G"
	"f"
	"g"
	"P"
	"h"
	"k"
	"l1"
	"E"
	"m"
]]

In [69]:
pylist(df3[-2]["plane_members"])

Python:
[shape: (10,)
Series: '' [str]
[
	"A"
	"B"
	"C"
	"c"
	"a"
	"b"
	"I"
	"G"
	"k"
	"D"
]]

In [40]:
o1 = [o.obj for o in df2.filter(pl.col("Type").is_in(["point"]))["object3d"]]

8-element Vector{Py}:
 Point3D(0, -8, 0)
 Point3D(6, 0, 0)
 Point3D(-6, 0, 0)
 Point3D(0, -3, 0)
 Point3D(0, -267/100, 0)
 Point3D(0, -267/100, 168/25)
 Point3D(-6, 0, 0)
 Point3D(0, -267/100, 168/25)

In [41]:
o0 = [o.obj for o in df2.filter(pl.col("Type").is_in(["plane"]))["object3d"]]

2-element Vector{Py}:
 Plane(Point3D(0, 0, 0), (0, 0, 1))
 Plane(Point3D(0, 0, 0), (1, 0, 0))

In [44]:
for p in o1
    println(p, ggbex_sympy.point_on_plane(p, o0[2]))
end

Point3D(0, -8, 0)True
Point3D(6, 0, 0)False
Point3D(-6, 0, 0)False
Point3D(0, -3, 0)True
Point3D(0, -267/100, 0)True
Point3D(0, -267/100, 168/25)True
Point3D(-6, 0, 0)False
Point3D(0, -267/100, 168/25)True

In [36]:
string(ggbex_sympy.plane_from_value("xyPlane: z = 0"))

"Plane(Point3D(0, 0, 0), (0, 0, 1))"

In [37]:
ggbex_sympy.plane_from_value("yzPlane: x = 0")

Python: Plane(Point3D(0, 0, 0), (1, 0, 0))

In [38]:
ggbex_sympy.Object3D.from_value_command(type_="plane", value="xyPlane: z = 0", command="xOyPlane")

Python: Object3D(kind='plane', obj=Plane(Point3D(0, 0, 0), (0, 0, 1)), value='xyPlane: z = 0', command='xOyPlane')

In [39]:
ggbex_sympy.object3d._try_surface_from_value("xyPlane: z = 0")

Python: None

In [40]:
for r in df.filter(pl.col("Type").is_in(["plane"]))["Name","Type","Command","Value"].iter_rows()
    println(ggbex_sympy.plane_from_value(r[3]))
end

Plane(Point3D(0, 0, 0), (0, 0, 1))
Plane(Point3D(0, 0, 0), (1, 0, 0))

In [65]:
using PythonCall

In [66]:
o = parse.(Float64, pyconvert(Vector{String}, refresh!(@ggb(:const("O"))).data["element"][0]["coords"][0].values()))[1:2]

2-element Vector{Float64}:
 0.0
 0.0

In [67]:
m = parse.(Float64, pyconvert(Vector{String}, refresh!(@ggb(:const("M"))).data["element"][0]["coords"][0].values()))[1:2]

2-element Vector{Float64}:
 -0.0857055406971006
 -5.99938784879706

In [68]:
r = parse.(Float64, pyconvert(Vector{String}, refresh!(@ggb(:const("R"))).data["element"][0]["coords"][0].values()))[1:2]

2-element Vector{Float64}:
  155.5041330408197
 1114.4462867925422

In [69]:
(r-m)' * (o-m)

6735.323076923079

In [70]:
using LinearAlgebra

In [71]:
(r-m) ⋅ (o-m)

6735.323076923079

In [72]:
@ggb r_1 = 4*sqrt(2)
@ggb r_2 = 3*sqrt(2)

r_2

In [73]:
r = parse.(Float64, pyconvert(Vector{String}, refresh!(@ggb(:const("R"))).data["element"][0]["coords"][0].values()))[1:2]

2-element Vector{Float64}:
  -43.518044962289
 -278.92198529393

In [74]:
(r-m) ⋅ (o-m)

-1641.0909069083293

In [75]:
@ggb :api getValueString(:M)

"M = (-0.0857055406971, -5.9993878487971)"

In [76]:
@ggb :api getXML(:M)

"<element type=\"point\" label=\"M\">\n\t<show object=\"true\" label=\"true\"/>\n\t<objColor r=\"21\" g=\"101\" b=\"192\" alpha=\"0\"/>\n\t<layer val=\"0\"/>\n\t<labelMode val=\"0\"/>\n\t<animation step=\"0.1\" type=\"1\" playing=\"false\"/>\n\t<pointSize val=\"5\"/>\n\t<pointStyle val=\"0\"/>\n\t<coords x=\"-0.0857055406971006\" y=\"-5.99938784879706\" z=\"1\"/>\n</element>\n"

In [77]:
@ggb :api getXcoord(:M)

-0.0857055406971006

In [78]:
@ggb :api getYcoord(:M)

-5.99938784879706

In [79]:
using PythonCall
ggb = pyimport("ggblab")
# ggb.connect_to_bridge() #port=51508)

Python: <module 'ggblab' from '/Users/manabu/work/ggblab/julia/GeoGebra.jl/.CondaPkg/.pixi/envs/default/lib/python3.14/site-packages/ggblab/__init__.py'>